name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa a cada 24 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Adicionar a cobrinha ao README
        uses: Platane/snk@master
        with:
          github_user_name: rodrigo-teixeira-silva
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit do resultado
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Atualizando a cobrinha do commit"
          git push
